spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/数据库名?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zzz123

mybatis:
  type-aliases-package: com.example.forum.entity
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  params: count=countSql
  supportMethodsArguments: true